<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class RfpsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('rfps')->delete();
        
        \DB::table('rfps')->insert(array (
            0 => 
            array (
                'id' => 12,
                'project_id' => 28,
                'rfp_number' => 'RFP-20260615-KPAW',
                'title' => 'CCTV INSTALLATION FOR PRODUCTION AREA - HO BUARAN',
                'description' => 'Project pekerjaan pemasangan CCTV Area Produksi HO Buaran sebanyak 17 Unit di Area Meja Kerja Tim Produksi dengan jenis CCTV - Dome',
                'tender_method' => 'invited',
                'technical_weightage' => 70,
                'financial_weightage' => 30,
                'submission_deadline' => '2026-06-19 12:00:00',
                'published_at' => '2026-06-15 13:08:04',
                'status' => 'awarded',
                'location_id' => 4,
                'created_at' => '2026-06-15 13:09:38',
                'updated_at' => '2026-06-19 14:54:10',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => NULL,
            ),
            1 => 
            array (
                'id' => 13,
                'project_id' => 30,
                'rfp_number' => 'RFP-20260622-YMEZ',
            'title' => 'Proyek Renovasi Fasad Delivery Point (Delpo) Phase 1',
            'description' => '<p>Pekerjaan renovasi fasad Delivery Point (Delpo) Phase 1 yang mencakup 4 lokasi, yaitu Delpo Pasar Minggu, Delpo Cinere, Delpo Rawamangun, dan Delpo Granada.Ruang lingkup pekerjaan per lokasi adalah sebagai berikut:</p><ol start="1"><li><p>Delpo Pasar Minggu - Penggantian panel signage logo Delpo.</p></li><li><p>2. Delpo Cinere - Penggantian panel signage logo Delpo.</p></li><li><p>Delpo Rawamangun - Penggantian panel signage logo Delpo.</p></li><li><p>Delpo Granada - Penggantian panel signage logo Delpo - Pengecatan area fasad bagian depan.</p></li></ol><p>Tujuan proyek ini adalah untuk meningkatkan tampilan dan keseragaman identitas visual Delivery Point sesuai standar.</p><p>Berikut adalah file sebagai referensi :</p><ol start="1"><li><p>Design Fasad Delivery Point : <a target="_blank" rel="noopener noreferrer nofollow" href="https://drive.google.com/file/d/1Ya0GQ8ZDt__7ofCs1EMZPZVRzMFSLvGN/view?usp=sharing">https://drive.google.com/file/d/1Ya0GQ8ZDt__7ofCs1EMZPZVRzMFSLvGN/view?usp=sharing</a></p></li><li><p>Template BoQ : <a target="_blank" rel="noopener noreferrer nofollow" href="https://docs.google.com/spreadsheets/d/1Z5Gc3JNEvSdqqeINom1myzMbMvsHE8C6bgL1nvTrauM/edit?gid=1042739307#gid=1042739307">https://docs.google.com/spreadsheets/d/1Z5Gc3JNEvSdqqeINom1myzMbMvsHE8C6bgL1nvTrauM/edit?gid=1042739307#gid=1042739307</a></p></li><li><p>Detail Lokasi Delivery Point : <a target="_blank" rel="noopener noreferrer nofollow" href="https://docs.google.com/spreadsheets/d/1K0Oa7V0nE4sFRcNNjcHctXwh2yp1-zNxnREC7ZxI_lw/edit?gid=79519372#gid=79519372">https://docs.google.com/spreadsheets/d/1K0Oa7V0nE4sFRcNNjcHctXwh2yp1-zNxnREC7ZxI_lw/edit?gid=79519372#gid=79519372</a></p><p></p></li></ol><p>Mohon dapat dikirimkan proposal penawaran dengan lampiran PDF dan Template BoQ paling lambat tanggal 23 Juni 2026 pukul 16.00</p><p>Penawaran Ditujukan kepada :</p><p>Procurement Department<br>PT Dapur Cokelat Indonesia<br>Jl. H. Niban Rimin No. 99, Buaran, Serpong, Tangerang Selatan</p>',
                'tender_method' => 'invited',
                'technical_weightage' => 60,
                'financial_weightage' => 40,
                'submission_deadline' => '2026-07-02 00:00:00',
                'published_at' => '2026-06-22 09:00:00',
                'status' => 'awarded',
                'location_id' => 12,
                'created_at' => '2026-06-22 08:50:51',
                'updated_at' => '2026-07-01 14:28:40',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => NULL,
            ),
            2 => 
            array (
                'id' => 15,
                'project_id' => 31,
                'rfp_number' => 'RFP-20260702-3FT3',
                'title' => 'PENGADAAN LAYANAN WHATSAPP BUSINESS API DAN OMNI CHANNEL CRM DI PT DAPUR COKELAT INDONESIA',
                'description' => '<p>Pengadaan Layanan WhatsApp Business API dan Omni Channel CRM yang akan digunakan oleh PT Dapur Cokelat Indonesia untuk meningkatkan performa layanan pelanggan, otomatisasi proses pemesanan, serta integrasi dengan sistem internal perusahaan.</p>',
                'tender_method' => 'invited',
                'technical_weightage' => 60,
                'financial_weightage' => 40,
                'submission_deadline' => '2026-07-30 12:00:00',
                'published_at' => '2026-07-02 08:59:07',
                'status' => 'awarded',
                'location_id' => 4,
                'created_at' => '2026-07-02 09:02:51',
                'updated_at' => '2026-07-08 17:42:02',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => NULL,
            ),
            3 => 
            array (
                'id' => 16,
                'project_id' => 47,
                'rfp_number' => 'RFP-20260706-CCUO',
                'title' => 'TESTING - RFP 02',
                'description' => '<p>Pengadaan Layanan WhatsApp Business API dan Omni Channel CRM yang akan digunakan oleh PT Dapur Cokelat Indonesia untuk meningkatkan performa layanan pelanggan, otomatisasi proses pemesanan, serta integrasi dengan sistem internal perusahaan.</p>',
                'tender_method' => 'invited',
                'technical_weightage' => 60,
                'financial_weightage' => 40,
                'submission_deadline' => '2026-08-05 17:28:53',
                'published_at' => '2026-07-06 17:28:53',
                'status' => 'published',
                'location_id' => 4,
                'created_at' => '2026-07-06 17:31:40',
                'updated_at' => '2026-07-21 17:02:46',
                'deleted_at' => NULL,
                'remark' => 'remark rfp 02',
                'external_notes' => 'RFP External notes 2',
            ),
            4 => 
            array (
                'id' => 17,
                'project_id' => 48,
                'rfp_number' => 'RFP-20260708-GI2Y',
                'title' => 'PROJECT REPOSISI OUTDOOR AC OUTLET DC MUARA KARANG',
                'description' => '<p>Pekerjaan dan material Reposisi outdoor AC Outlet DC Muara Karang.<br><br>SCOPE OF WORK :<br>- Mob. - Demob pekerja &amp; Alat<br>- Pengadaan &amp; pemasangan instalasi pipa AC 2PK<br>- Bongkar pasang outdoor AC 2PK<br>- Pengisian freon AC<br>- Pembersihan akhir<br><br>Untuk detail kondisi, mohon dilakukan survey di lokasi Outlet DC Muara Karang dan kordinasi dengan OM - Pak Berry</p>',
                'tender_method' => 'invited',
                'technical_weightage' => 60,
                'financial_weightage' => 40,
                'submission_deadline' => '2026-08-07 20:37:17',
                'published_at' => '2026-07-08 20:37:17',
                'status' => 'awarded',
                'location_id' => 12,
                'created_at' => '2026-07-08 20:38:58',
                'updated_at' => '2026-07-09 12:57:44',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => NULL,
            ),
            5 => 
            array (
                'id' => 18,
                'project_id' => 54,
                'rfp_number' => 'RFP-20260717-YPI4',
                'title' => 'RENOVASI OUTLET MENTENG',
                'description' => '<p>Project Renovasi Outlet Menteng dengan melaksanakan pekerjaan perbaikan meliputi :<br><br>1. Perbaikan saluran pembuangan kamar mandi mampet hingga menyebabkan bocor/banjir ke bawah</p><p>2. Perbesaran saluran air hujan dari lantai 3</p><p>3. Pembuatan saluran dari lantai 1 ke selokan depan</p><p>4. Cat plafon area depan &amp; area display</p><p>5. Perbaikan tambahan sink mampet<br><br>Mohon melengkapi template BoQ yang tercantum pada link.</p>',
                'tender_method' => 'invited',
                'technical_weightage' => 60,
                'financial_weightage' => 40,
                'submission_deadline' => '2026-07-24 12:00:00',
                'published_at' => '2026-07-17 20:52:12',
                'status' => 'awarded',
                'location_id' => 12,
                'created_at' => '2026-07-17 20:55:05',
                'updated_at' => '2026-07-24 12:54:14',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => NULL,
            ),
            6 => 
            array (
                'id' => 19,
                'project_id' => 57,
                'rfp_number' => 'RFP-20260721-EIYV',
                'title' => 'RFP multiple project 1',
                'description' => '<p><strong><s>Description RFP testing</s></strong></p>',
                'tender_method' => 'invited',
                'technical_weightage' => 60,
                'financial_weightage' => 40,
                'submission_deadline' => '2026-08-20 17:48:39',
                'published_at' => '2026-07-21 17:48:39',
                'status' => 'published',
                'location_id' => 4,
                'created_at' => '2026-07-21 17:50:03',
                'updated_at' => '2026-07-21 17:50:03',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => NULL,
            ),
            7 => 
            array (
                'id' => 20,
                'project_id' => 57,
                'rfp_number' => 'RFP-20260721-TJNQ',
                'title' => 'RFP Test Project 0 Value',
                'description' => '<h3>RFP For Test Project 0 Value 2</h3>',
                'tender_method' => 'invited',
                'technical_weightage' => 60,
                'financial_weightage' => 40,
                'submission_deadline' => '2026-08-20 17:51:04',
                'published_at' => '2026-07-21 17:51:04',
                'status' => 'published',
                'location_id' => 4,
                'created_at' => '2026-07-21 17:51:47',
                'updated_at' => '2026-07-21 17:51:47',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => NULL,
            ),
            8 => 
            array (
                'id' => 21,
                'project_id' => 63,
                'rfp_number' => 'RFP-20260725-XTWB',
                'title' => 'RENOVASI DELPO PALMERAH',
                'description' => '<p>Ruang Lingkup Pekerjaan Renovasi Delpo Palmerah : untuk melaksanakan pekerjaan perbaikan dan renovasi area delpo yang meliputi <br><br> Pekerjaan servis atap<br> Partisi gibsum rangka hollow dinding samping<br> Pengecatan plafon<br> Pengecatan dinding<br> penggantian instalasi sink gestrap<br> Perkuatan balokan dak cor teras<br> Tiang perkuatan balokan teras berikut bungkus partisi<br> Pembersihan akhir</p>',
                'tender_method' => 'invited',
                'technical_weightage' => 60,
                'financial_weightage' => 40,
                'submission_deadline' => '2026-07-29 12:00:00',
                'published_at' => '2026-07-25 08:11:26',
                'status' => 'awarded',
                'location_id' => 12,
                'created_at' => '2026-07-25 08:13:43',
                'updated_at' => '2026-07-29 21:28:27',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => NULL,
            ),
            9 => 
            array (
                'id' => 22,
                'project_id' => 57,
                'rfp_number' => 'RFP-20260804-BTB8',
                'title' => 'TESTING RFP',
                'description' => '<h2><u>Testing RFP by IT</u></h2>',
                'tender_method' => 'invited',
                'technical_weightage' => 60,
                'financial_weightage' => 40,
                'submission_deadline' => '2026-09-03 10:16:39',
                'published_at' => '2026-08-04 10:16:39',
                'status' => 'published',
                'location_id' => 4,
                'created_at' => '2026-08-04 10:17:15',
                'updated_at' => '2026-08-04 10:17:15',
                'deleted_at' => NULL,
                'remark' => 'testing rfp',
                'external_notes' => 'test rfp',
            ),
            10 => 
            array (
                'id' => 23,
                'project_id' => 76,
                'rfp_number' => 'RFP-20260804-4E1C',
                'title' => 'TESTING RFP 02',
                'description' => '<h2><strong><em>test rfp 02</em></strong></h2>',
                'tender_method' => 'invited',
                'technical_weightage' => 60,
                'financial_weightage' => 40,
                'submission_deadline' => '2026-09-03 10:17:45',
                'published_at' => '2026-08-04 10:17:45',
                'status' => 'published',
                'location_id' => 4,
                'created_at' => '2026-08-04 10:18:22',
                'updated_at' => '2026-08-04 10:18:22',
                'deleted_at' => NULL,
                'remark' => 'test rfp by it',
                'external_notes' => 'test rfp only',
            ),
            11 => 
            array (
                'id' => 24,
                'project_id' => 144,
                'rfp_number' => 'RFP-20260903-RR2W',
                'title' => 'PEKERJAAN RENOVASI / PARTISI K3 41 TEKNO',
            'description' => '<p>Pekerjaan Renovasi / Partisi Warehouse K3 41 Tekno mencakup Sipil, Interior, &amp; ME (Mekanikal Elektrikal) yang mencakup :<br><br>1. Mobilisasi/demobilisasi alat kerja, persiapan tempat kerja, serta pembersihan akhir area proyek setelah pekerjaan selesai.<br>2. Pengadaan dan pemasangan dinding partisi 2 sisi (termasuk penambahan pelapis GRC 6mm jika diperlukan sesuai spesifikasi teknis).<br>3. Pemasangan rangka dan penutup plafon area K3 41 Tekno.<br>4. Pengadaan dan pemasangan 1 set/unit pintu beserta kusen aluminium, rel sliding, serta pekerjaan opening pintu.<br>5.Pengecatan interior dinding/partisi dan plafon dengan cat emulsi berkualitas sesuai spesifikasi teknis.<br>6.• Pengadaan &amp; instalasi pipa AC 1.5 PK • Instalasi jalur pembuangan / pipa dry AC • Pemasangan breket AC &amp; titik power AC<br>7. • Instalasi titik lampu &amp; saklar • Pengadaan &amp; pemasangan armature lampu Downlight LED • Pengadaan &amp; pemasangan saklar</p>',
                'tender_method' => 'invited',
                'technical_weightage' => 60,
                'financial_weightage' => 40,
                'submission_deadline' => '2026-10-03 10:11:32',
                'published_at' => '2026-09-03 10:11:32',
                'status' => 'awarded',
                'location_id' => 4,
                'created_at' => '2026-09-03 10:12:54',
                'updated_at' => '2026-09-08 08:38:34',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => NULL,
            ),
        ));
        
        
    }
}