<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class RfqsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('rfqs')->delete();
        
        \DB::table('rfqs')->insert(array (
            0 => 
            array (
                'id' => 9,
                'project_id' => 3,
                'rfq_number' => 'RFQ-20260310-HSEC',
                'type' => 'invited_only',
                'status' => 'negotiation',
                'location_id' => 7,
                'project_type' => 'project',
                'published_at' => '2026-03-10 13:43:33',
                'created_at' => '2026-03-10 13:43:59',
                'updated_at' => '2026-07-20 21:51:54',
                'deleted_at' => NULL,
                'remark' => 'TESTING TESTING',
                'external_notes' => NULL,
            ),
            1 => 
            array (
                'id' => 13,
                'project_id' => 25,
                'rfq_number' => 'RFQ-20260605-E9GB',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 4,
                'project_type' => 'project',
                'published_at' => '2026-06-05 17:52:30',
                'created_at' => '2026-06-05 17:55:18',
                'updated_at' => '2026-07-21 16:42:12',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => 'RFQ External Notes',
            ),
            2 => 
            array (
                'id' => 17,
                'project_id' => 29,
                'rfq_number' => 'RFQ-20260616-LDYM',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 4,
                'project_type' => 'project',
                'published_at' => '2026-06-16 15:10:45',
                'created_at' => '2026-06-16 15:10:56',
                'updated_at' => '2026-06-27 15:37:39',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => NULL,
            ),
            3 => 
            array (
                'id' => 18,
                'project_id' => 32,
                'rfq_number' => 'RFQ-20260625-P6XI',
                'type' => 'invited_only',
                'status' => 'negotiation',
                'location_id' => 4,
                'project_type' => 'project',
                'published_at' => '2026-06-25 16:56:20',
                'created_at' => '2026-06-25 17:03:43',
                'updated_at' => '2026-06-25 17:19:16',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => NULL,
            ),
            4 => 
            array (
                'id' => 28,
                'project_id' => 42,
                'rfq_number' => 'RFQ-20260703-1L5A',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 4,
                'project_type' => 'purchase_request',
                'published_at' => '2026-07-03 17:19:36',
                'created_at' => '2026-07-03 17:40:27',
                'updated_at' => '2026-07-03 18:25:25',
                'deleted_at' => NULL,
            'remark' => 'PR- 1234 ( PR testing order Telur )',
                'external_notes' => NULL,
            ),
            5 => 
            array (
                'id' => 31,
                'project_id' => 45,
                'rfq_number' => 'RFQ-20260706-RV8C',
                'type' => 'invited_only',
                'status' => 'published',
                'location_id' => 4,
                'project_type' => 'project',
                'published_at' => '2026-07-06 17:13:42',
                'created_at' => '2026-07-06 17:14:08',
                'updated_at' => '2026-07-21 16:49:18',
                'deleted_at' => NULL,
                'remark' => 'remark rfq',
                'external_notes' => 'RFQ External Notes 2',
            ),
            6 => 
            array (
                'id' => 32,
                'project_id' => 49,
                'rfq_number' => 'RFQ-20260710-TNWI',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 4,
                'project_type' => 'purchase_request',
                'published_at' => '2026-07-10 17:32:42',
                'created_at' => '2026-07-10 17:43:38',
                'updated_at' => '2026-07-14 16:16:50',
                'deleted_at' => NULL,
                'remark' => 'Pengajuan laptop untuk accounting ',
                'external_notes' => NULL,
            ),
            7 => 
            array (
                'id' => 33,
                'project_id' => 50,
                'rfq_number' => 'RFQ-20260713-P1MT',
                'type' => 'invited_only',
                'status' => 'published',
                'location_id' => 12,
                'project_type' => 'purchase_request',
                'published_at' => '2026-07-13 15:56:15',
                'created_at' => '2026-07-13 16:16:01',
                'updated_at' => '2026-07-13 16:16:01',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => NULL,
            ),
            8 => 
            array (
                'id' => 34,
                'project_id' => 51,
                'rfq_number' => 'RFQ-20260714-RHST',
                'type' => 'invited_only',
                'status' => 'published',
                'location_id' => 4,
                'project_type' => 'purchase_request',
                'published_at' => '2026-07-14 16:54:38',
                'created_at' => '2026-07-14 16:58:31',
                'updated_at' => '2026-07-14 16:58:31',
                'deleted_at' => NULL,
            'remark' => 'PR- 1234 ( PR testing order Telur )',
                'external_notes' => NULL,
            ),
            9 => 
            array (
                'id' => 35,
                'project_id' => 52,
                'rfq_number' => 'RFQ-20260716-5DKN',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 4,
                'project_type' => 'project',
                'published_at' => '2026-07-16 11:24:34',
                'created_at' => '2026-07-16 11:25:35',
                'updated_at' => '2026-07-22 18:07:27',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => NULL,
            ),
            10 => 
            array (
                'id' => 36,
                'project_id' => 55,
                'rfq_number' => 'RFQ-20260720-UNRN',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 4,
                'project_type' => 'purchase_request',
                'published_at' => '2026-07-20 16:13:20',
                'created_at' => '2026-07-20 16:39:02',
                'updated_at' => '2026-07-23 11:21:41',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => NULL,
            ),
            11 => 
            array (
                'id' => 37,
                'project_id' => 57,
                'rfq_number' => 'RFQ-20260721-4DQC',
                'type' => 'invited_only',
                'status' => 'published',
                'location_id' => 4,
                'project_type' => 'project',
                'published_at' => '2026-07-21 17:52:24',
                'created_at' => '2026-07-21 17:57:27',
                'updated_at' => '2026-07-21 17:57:27',
                'deleted_at' => NULL,
                'remark' => 'internal remark rfq',
                'external_notes' => 'external notes rfq',
            ),
            12 => 
            array (
                'id' => 38,
                'project_id' => 58,
                'rfq_number' => 'RFQ-20260721-GJWC',
                'type' => 'invited_only',
                'status' => 'negotiation',
                'location_id' => 4,
                'project_type' => 'purchase_request',
                'published_at' => '2026-07-21 17:49:16',
                'created_at' => '2026-07-21 17:57:28',
                'updated_at' => '2026-07-21 18:10:32',
                'deleted_at' => NULL,
                'remark' => 'PR #1234',
                'external_notes' => 'Mohon informasi bottom harga telur hari ini,  di qty 1050kg untuk pengiriman besok 23/7/2026 di tunggu sampai jam 12.00  terimakasih',
            ),
            13 => 
            array (
                'id' => 39,
                'project_id' => 59,
                'rfq_number' => 'RFQ-20260722-29GU',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 4,
                'project_type' => 'purchase_request',
                'published_at' => '2026-07-22 11:26:36',
                'created_at' => '2026-07-22 11:45:57',
                'updated_at' => '2026-07-22 12:30:30',
                'deleted_at' => NULL,
                'remark' => 'PR NO 1234',
                'external_notes' => 'Mohon informasi update bottom harga telur hari ini tanggal 23 Juli 2026, dengan kuantiti 1050kg untuk pengiriman besok di tanggal 24 Juli 2026. Kami tunggu informasinya sampai jam 12.00 siang. Terimakasih',
            ),
            14 => 
            array (
                'id' => 40,
                'project_id' => 60,
                'rfq_number' => 'RFQ-20260722-XIYG',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 4,
                'project_type' => 'purchase_request',
                'published_at' => '2026-07-22 14:01:33',
                'created_at' => '2026-07-22 14:47:00',
                'updated_at' => '2026-07-24 10:55:41',
                'deleted_at' => NULL,
                'remark' => 'Untuk PR #4955 #4783 #4782',
                'external_notes' => NULL,
            ),
            15 => 
            array (
                'id' => 41,
                'project_id' => 61,
                'rfq_number' => 'RFQ-20260724-JWNF',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 4,
                'project_type' => 'purchase_request',
                'published_at' => '2026-07-24 10:07:09',
                'created_at' => '2026-07-24 10:19:33',
                'updated_at' => '2026-07-24 14:07:21',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => NULL,
            ),
            16 => 
            array (
                'id' => 42,
                'project_id' => 62,
                'rfq_number' => 'RFQ-20260724-UF7R',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 4,
                'project_type' => 'purchase_request',
                'published_at' => '2026-07-24 15:05:03',
                'created_at' => '2026-07-24 15:16:25',
                'updated_at' => '2026-07-30 15:12:02',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => NULL,
            ),
            17 => 
            array (
                'id' => 43,
                'project_id' => 64,
                'rfq_number' => 'RFQ-20260727-7K6Y',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 4,
                'project_type' => 'purchase_request',
                'published_at' => '2026-07-27 11:23:40',
                'created_at' => '2026-07-27 13:19:18',
                'updated_at' => '2026-07-28 10:06:15',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => NULL,
            ),
            18 => 
            array (
                'id' => 44,
                'project_id' => 65,
                'rfq_number' => 'RFQ-20260727-I6XC',
                'type' => 'invited_only',
                'status' => 'published',
                'location_id' => 4,
                'project_type' => 'purchase_request',
                'published_at' => '2026-07-27 22:33:40',
                'created_at' => '2026-07-27 22:44:07',
                'updated_at' => '2026-07-27 22:44:07',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => 'Mohon informasi update bottom harga telur hari ini tanggal 28 Juli 2026, dengan kuantiti 1050kg untuk pengiriman besok di tanggal 29 Juli 2026. Kami tunggu informasinya sampai jam 12.00 siang. Terimakasih',
            ),
            19 => 
            array (
                'id' => 45,
                'project_id' => 66,
                'rfq_number' => 'RFQ-20260728-6GXY',
                'type' => 'invited_only',
                'status' => 'negotiation',
                'location_id' => 4,
                'project_type' => 'purchase_request',
                'published_at' => '2026-07-28 14:13:47',
                'created_at' => '2026-07-28 14:17:43',
                'updated_at' => '2026-07-28 14:20:18',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => 'Mohon informasi update bottom harga telur hari ini tanggal 28 Juli 2026, dengan kuantiti 1050kg untuk pengiriman besok di tanggal 29 Juli 2026. Kami tunggu informasinya sampai jam 12.00 siang. Terimakasih',
            ),
            20 => 
            array (
                'id' => 46,
                'project_id' => 67,
                'rfq_number' => 'RFQ-20260728-QISP',
                'type' => 'invited_only',
                'status' => 'published',
                'location_id' => 4,
                'project_type' => 'purchase_request',
                'published_at' => '2026-07-28 13:44:44',
                'created_at' => '2026-07-28 15:03:50',
                'updated_at' => '2026-07-28 15:03:50',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => NULL,
            ),
            21 => 
            array (
                'id' => 47,
                'project_id' => 68,
                'rfq_number' => 'RFQ-20260728-BO9K',
                'type' => 'invited_only',
                'status' => 'negotiation',
                'location_id' => 4,
                'project_type' => 'purchase_request',
                'published_at' => '2026-07-28 15:05:01',
                'created_at' => '2026-07-28 15:06:32',
                'updated_at' => '2026-07-28 15:09:47',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => 'Mohon informasi update bottom harga telur hari ini tanggal 28 Juli 2026, dengan kuantiti 1050kg untuk pengiriman besok di tanggal 29 Juli 2026. Kami tunggu informasinya sampai jam 12.00 siang. Terimakasih',
            ),
            22 => 
            array (
                'id' => 48,
                'project_id' => 69,
                'rfq_number' => 'RFQ-20260728-F7LZ',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 4,
                'project_type' => 'purchase_request',
                'published_at' => '2026-07-28 15:24:50',
                'created_at' => '2026-07-28 15:30:51',
                'updated_at' => '2026-08-03 12:31:29',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => NULL,
            ),
            23 => 
            array (
                'id' => 49,
                'project_id' => 70,
                'rfq_number' => 'RFQ-20260728-56ZD',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 4,
                'project_type' => 'purchase_request',
                'published_at' => '2026-07-28 15:39:04',
                'created_at' => '2026-07-28 16:04:51',
                'updated_at' => '2026-08-05 16:57:59',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => NULL,
            ),
            24 => 
            array (
                'id' => 50,
                'project_id' => 71,
                'rfq_number' => 'RFQ-20260730-PPAR',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 4,
                'project_type' => 'purchase_request',
                'published_at' => '2026-07-30 13:44:49',
                'created_at' => '2026-07-30 14:41:04',
                'updated_at' => '2026-07-31 17:00:11',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => NULL,
            ),
            25 => 
            array (
                'id' => 51,
                'project_id' => 72,
                'rfq_number' => 'RFQ-20260731-GPZV',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 4,
                'project_type' => 'purchase_request',
                'published_at' => '2026-07-31 13:36:33',
                'created_at' => '2026-07-31 13:45:57',
                'updated_at' => '2026-07-31 15:20:49',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => 'Selamat siang Kami Mohon informasi  update bottom harga telur tgl 31/07/2026 hari ini,  dengan qty 600kg untuk pengiriman tgl 01/8/2026, dan 900kg untuk pengiriman tgl 03/08/2026 . Kami tunggu informasinya sampai jam 14.30 WIB. Terimakasih .',
            ),
            26 => 
            array (
                'id' => 52,
                'project_id' => 73,
                'rfq_number' => 'RFQ-20260731-N2DA',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 4,
                'project_type' => 'purchase_request',
                'published_at' => '2026-07-31 13:46:08',
                'created_at' => '2026-07-31 13:49:10',
                'updated_at' => '2026-07-31 15:19:23',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => 'Selamat siang Kami Mohon informasi  update bottom harga telur tgl 31/07/2026 hari ini,  dengan qty 600kg untuk pengiriman tgl 01/8/2026, dan 900kg untuk pengiriman tgl 03/08/2026 . Kami tunggu informasinya sampai jam 14.30 WIB. Terimakasih .',
            ),
            27 => 
            array (
                'id' => 53,
                'project_id' => 74,
                'rfq_number' => 'RFQ-20260803-C8K0',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 4,
                'project_type' => 'purchase_request',
                'published_at' => '2026-08-03 10:30:10',
                'created_at' => '2026-08-03 10:34:14',
                'updated_at' => '2026-08-03 13:05:48',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => 'Selamat siang Kami Mohon informasi update bottom harga telur tgl 03/082026 hari ini, dengan qty 900kg untuk pengiriman tgl 04/8/2026, . Kami tunggu informasinya sampai jam 14.30 WIB. Terimakasih .',
            ),
            28 => 
            array (
                'id' => 54,
                'project_id' => 75,
                'rfq_number' => 'RFQ-20260803-OKA8',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 12,
                'project_type' => 'purchase_request',
                'published_at' => '2026-08-03 16:01:09',
                'created_at' => '2026-08-03 16:24:05',
                'updated_at' => '2026-08-05 16:04:46',
                'deleted_at' => NULL,
                'remark' => NULL,
            'external_notes' => '<p>Pengadaan Media Promosi Umbul-Umbul Kemerdekaan  Mohon dibuatkan penawaran harga untuk pengadaan media promosi Umbul-Umbul Kemerdekaan dengan rincian sebagai berikut:</p><p>A. Area Jabodetabek  Jumlah outlet: 18 outlet (detail lokasi terlampir)  Mohon disampaikan penawaran dengan opsi pemasangan:</p><p>A1. Pemasangan 7 titik dengan durasi 7 hari.</p><p>A2. Pemasangan 7 titik dengan durasi 14 hari.</p><p></p><p>B. Area Bandung  Jumlah outlet: 1 outlet (detail lokasi terlampir)</p><p>B1. Pemasangan 7 titik dengan durasi 7 hari.</p><p>B2. Pemasangan 7 titik dengan durasi 14 hari.</p><p></p><p>C. Area Medan  Jumlah outlet: 1 outlet (detail lokasi terlampir)  Mohon disampaikan penawaran dengan opsi pemasangan:</p><p>C1. Pemasangan 7 titik dengan durasi 7 hari.</p><p>C2. Pemasangan 7 titik dengan durasi 14 hari.</p><p>Mohon agar penawaran mencantumkan rincian biaya untuk masing-masing opsi, yang meliputi:</p><ol start="1"><li><p>Biaya Cetak, Pemasangan, dan Pembongkaran.</p></li><li><p>Biaya Pengurusan Izin .</p></li></ol><p>Selain itu, mohon mencantumkan spesifikasi material umbul-umbul</p><p><br></p>',
            ),
            29 => 
            array (
                'id' => 55,
                'project_id' => 78,
                'rfq_number' => 'RFQ-20260804-G5RQ',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 4,
                'project_type' => 'purchase_request',
                'published_at' => '2026-08-04 10:15:15',
                'created_at' => '2026-08-04 10:23:15',
                'updated_at' => '2026-08-04 11:30:38',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => '<p>Selamat siang Kami Mohon informasi update bottom harga telur tgl 04/08/2026 hari ini, dengan qty 1200kg untuk pengiriman tgl 05/08/2026, . Kami tunggu informasinya sampai jam 12.30 WIB. Terimakasih .</p>',
            ),
            30 => 
            array (
                'id' => 56,
                'project_id' => 77,
                'rfq_number' => 'RFQ-20260804-QO9Q',
                'type' => 'invited_only',
                'status' => 'negotiation',
                'location_id' => 4,
                'project_type' => 'project',
                'published_at' => '2026-08-04 10:23:20',
                'created_at' => '2026-08-04 10:23:45',
                'updated_at' => '2026-08-10 17:39:25',
                'deleted_at' => NULL,
                'remark' => 'Test RFQ project',
                'external_notes' => '<p>Test RFQ project</p>',
            ),
            31 => 
            array (
                'id' => 57,
                'project_id' => 79,
                'rfq_number' => 'RFQ-20260805-DVLF',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 4,
                'project_type' => 'purchase_request',
                'published_at' => '2026-08-05 10:00:50',
                'created_at' => '2026-08-05 10:10:04',
                'updated_at' => '2026-08-05 11:30:00',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => '<p>Selamat siang, Kami mohon informasi update bottom harga telur ayam fresh hari ini tgl 05/08/2026 , untuk pengiriman tgl 06/08/2026 dengan qty 750kg. Kami tunggu informasinya sampai dengan jam 12.30 WIB. Terimakasih</p>',
            ),
            32 => 
            array (
                'id' => 58,
                'project_id' => 80,
                'rfq_number' => 'RFQ-20260806-1NWO',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 4,
                'project_type' => 'purchase_request',
                'published_at' => '2026-08-06 11:11:14',
                'created_at' => '2026-08-06 11:37:37',
                'updated_at' => '2026-08-06 13:21:47',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => '<p>Selamat siang, Kami mohon informasi update bottom harga telur ayam fresh hari ini tgl 06/08/2026 , untuk pengiriman tgl 07/08/2026 dengan qty 750kg. Kami tunggu informasinya sampai dengan jam 12.30 WIB. Terimakasih</p>',
            ),
            33 => 
            array (
                'id' => 59,
                'project_id' => 81,
                'rfq_number' => 'RFQ-20260806-ECIO',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 4,
                'project_type' => 'purchase_request',
                'published_at' => '2026-08-06 12:41:52',
                'created_at' => '2026-08-06 13:47:21',
                'updated_at' => '2026-08-20 11:05:42',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => '<p>PT Dapur Cokelat Indonesia mengundang penyedia berpengalaman untuk mengikuti tender <strong>Pengadaan Box Cake Natal 2026</strong> <strong>Region - JABODETABEK.</strong></p><p>Ruang lingkup meliputi : Produksi, Pengemasan, dan pengiriman box cake sesuai spesifikasi yang telah ditentukan.</p><p>Persyaratan peserta:</p><ul><li><p>Berpengalaman dalam produksi kemasan kertas/karton untuk industri makanan.</p></li><li><p>Memiliki kapasitas produksi yang memadai.</p></li><li><p>Menjamin kualitas material, cetak, dan konstruksi produk.</p></li><li><p>Bersedia mengikuti seluruh tahapan tender.<br></p></li></ul><p>Dokumen Penawaran ditujukan kepada Departemen Procurement PT Dapur Cokelat Indonesia dengan mencantumkan informasi sebagai berikut :</p><ul><li><p>Harga penawaran.</p></li><li><p>Spesifikasi material.</p></li><li><p>Lead time produksi dan pengiriman.</p></li></ul><p>Evaluasi dilakukan berdasarkan kesesuaian spesifikasi, kualitas, harga, kapasitas produksi, ketepatan waktu, dan kelengkapan administrasi.</p><p>Batas waktu pengiriman penawaran: <strong>10 Agustus 2026 pukul 12.00 WIB</strong>.</p>',
            ),
            34 => 
            array (
                'id' => 60,
                'project_id' => 82,
                'rfq_number' => 'RFQ-20260806-VISF',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 7,
                'project_type' => 'purchase_request',
                'published_at' => '2026-08-06 17:09:40',
                'created_at' => '2026-08-06 17:24:59',
                'updated_at' => '2026-08-26 13:51:21',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => '<p>PT Dapur Cokelat Indonesia mengundang penyedia berpengalaman untuk mengikuti tender Pengadaan Box Cake Natal 2026 Region - EX-JABO</p><p>Ruang lingkup meliputi : Produksi, Pengemasan, dan pengiriman box cake sesuai spesifikasi yang telah ditentukan.</p><p>Persyaratan peserta:</p><p>Berpengalaman dalam produksi kemasan kertas/karton untuk industri makanan.</p><p>Memiliki kapasitas produksi yang memadai.</p><p>Menjamin kualitas material, cetak, dan konstruksi produk.</p><p>Bersedia mengikuti seluruh tahapan tender.</p><p>Dokumen Penawaran ditujukan kepada Departemen Procurement PT Dapur Cokelat Indonesia dengan mencantumkan informasi sebagai berikut :</p><ol start="1"><li><p>Harga penawaran.</p></li><li><p>Spesifikasi material.</p></li><li><p>Lead time produksi dan pengiriman.</p></li></ol><p>Evaluasi dilakukan berdasarkan kesesuaian spesifikasi, kualitas, harga, kapasitas produksi, ketepatan waktu, dan kelengkapan administrasi.</p><p>Batas waktu pengiriman penawaran: <strong>10 Agustus 2026 pukul 12.00 WIB.</strong><br></p>',
            ),
            35 => 
            array (
                'id' => 61,
                'project_id' => 83,
                'rfq_number' => 'RFQ-20260807-IIJO',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 4,
                'project_type' => 'purchase_request',
                'published_at' => '2026-08-07 10:42:18',
                'created_at' => '2026-08-07 10:46:35',
                'updated_at' => '2026-08-07 11:34:56',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => '<p>Selamat siang, Kami mohon informasi update bottom harga telur ayam fresh hari ini tgl 07/08/2026 , untuk pengiriman tgl 08/08/2026 dengan qty 900kg. Kami tunggu informasinya sampai dengan jam 12.30 WIB. Terimakasih</p>',
            ),
            36 => 
            array (
                'id' => 62,
                'project_id' => 84,
                'rfq_number' => 'RFQ-20260807-1MXU',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 4,
                'project_type' => 'purchase_request',
                'published_at' => '2026-08-07 10:46:51',
                'created_at' => '2026-08-07 10:49:14',
                'updated_at' => '2026-08-07 11:35:42',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => '<p>Selamat siang, Kami mohon informasi update bottom harga telur ayam fresh hari ini tgl 05/08/2026 , untuk pengiriman tgl 10/08/2026 dengan qty 1050kg. Kami tunggu informasinya sampai dengan jam 12.30 WIB. Terimakasih</p>',
            ),
            37 => 
            array (
                'id' => 63,
                'project_id' => 85,
                'rfq_number' => 'RFQ-20260810-UYJW',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 4,
                'project_type' => 'purchase_request',
                'published_at' => '2026-08-10 11:20:42',
                'created_at' => '2026-08-10 11:24:07',
                'updated_at' => '2026-08-10 13:23:23',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => '<p>Selamat siang, Kami mohon informasi update bottom harga telur ayam fresh hari ini tgl 10/08/2026 , untuk pengiriman tgl 11/08/2026 dengan qty 900kg. Kami tunggu informasinya sampai dengan jam 13.00 WIB. Terimakasih</p>',
            ),
            38 => 
            array (
                'id' => 64,
                'project_id' => 86,
                'rfq_number' => 'RFQ-20260811-AK3A',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 4,
                'project_type' => 'purchase_request',
                'published_at' => '2026-08-11 10:16:13',
                'created_at' => '2026-08-11 10:21:54',
                'updated_at' => '2026-08-11 11:06:49',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => '<p>Selamat siang, Kami mohon informasi update bottom harga telur ayam fresh hari ini tgl 11/08/2026 , untuk pengiriman tgl 12/08/2026 dengan qty 1200kg. Kami tunggu informasinya sampai dengan jam 13.00 WIB. Terimakasih</p>',
            ),
            39 => 
            array (
                'id' => 65,
                'project_id' => 87,
                'rfq_number' => 'RFQ-20260812-K3FJ',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 4,
                'project_type' => 'purchase_request',
                'published_at' => '2026-08-12 10:36:46',
                'created_at' => '2026-08-12 10:39:09',
                'updated_at' => '2026-08-12 11:00:43',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => '<p>Selamat siang, Kami mohon informasi update bottom harga telur ayam fresh hari ini tgl 12/08/2026 , untuk pengiriman tgl 13/08/2026 dengan qty 900kg. Kami tunggu informasinya sampai dengan jam 12.30 WIB. Terimakasih</p>',
            ),
            40 => 
            array (
                'id' => 66,
                'project_id' => 88,
                'rfq_number' => 'RFQ-20260813-R3PX',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 4,
                'project_type' => 'purchase_request',
                'published_at' => '2026-08-13 09:56:07',
                'created_at' => '2026-08-13 10:05:57',
                'updated_at' => '2026-08-13 17:17:10',
                'deleted_at' => NULL,
                'remark' => NULL,
            'external_notes' => '<p>Specification :</p><p>Graphics : NVIDIA® GeForce RTX™ 3050 6GB GDDR6 (</p><p>Prosesor: Intel Core i5-13420H 13th</p><p>Display : 15.6 inci Full HD IPS</p><p>Memory : 2*8GB DDR4, Upgradable (2x SO-DIMM DDR4 Slot)</p><p>Storage : 512GB SSD</p>',
            ),
            41 => 
            array (
                'id' => 67,
                'project_id' => 89,
                'rfq_number' => 'RFQ-20260813-U2EK',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 4,
                'project_type' => 'purchase_request',
                'published_at' => '2026-08-13 10:28:18',
                'created_at' => '2026-08-13 10:31:31',
                'updated_at' => '2026-08-13 10:59:40',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => '<p>Selamat siang, Kami mohon informasi update bottom harga telur ayam fresh hari ini tgl 13/08/2026 , untuk pengiriman tgl 14/08/2026 dengan qty 1050kg. Kami tunggu informasinya sampai dengan jam 12.30 WIB. Terimakasih</p>',
            ),
            42 => 
            array (
                'id' => 68,
                'project_id' => 90,
                'rfq_number' => 'RFQ-20260813-LSRE',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 4,
                'project_type' => 'purchase_request',
                'published_at' => '2026-08-13 15:59:45',
                'created_at' => '2026-08-13 16:12:51',
                'updated_at' => '2026-08-19 10:52:35',
                'deleted_at' => NULL,
            'remark' => 'PR-SS-26-07-5061 ( MESIN CUP SEALER ICE CHOCO 2 unit ) ',
                'external_notes' => '<p></p>',
            ),
            43 => 
            array (
                'id' => 69,
                'project_id' => 91,
                'rfq_number' => 'RFQ-20260814-COXJ',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 4,
                'project_type' => 'purchase_request',
                'published_at' => '2026-08-14 10:25:59',
                'created_at' => '2026-08-14 10:30:20',
                'updated_at' => '2026-08-14 10:53:13',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => '<p>Selamat siang, Kami mohon informasi update bottom harga telur ayam fresh hari ini tgl 14/08/2026 , untuk pengiriman tgl 15/08/2026 dengan qty 750kg. Kami tunggu informasinya sampai dengan jam 12.30 WIB. Terimakasih</p>',
            ),
            44 => 
            array (
                'id' => 70,
                'project_id' => 92,
                'rfq_number' => 'RFQ-20260814-MOBT',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 4,
                'project_type' => 'purchase_request',
                'published_at' => '2026-08-14 10:30:47',
                'created_at' => '2026-08-14 10:34:38',
                'updated_at' => '2026-08-14 10:55:13',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => '<p>Selamat siang, Kami mohon informasi update bottom harga telur ayam fresh hari ini tgl 14/08/2026 , untuk pengiriman tgl 18/08/2026 dengan qty 900kg. Kami tunggu informasinya sampai dengan jam 12.30 WIB. Terimakasih</p>',
            ),
            45 => 
            array (
                'id' => 71,
                'project_id' => 93,
                'rfq_number' => 'RFQ-20260818-GENZ',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 4,
                'project_type' => 'purchase_request',
                'published_at' => '2026-08-18 09:27:41',
                'created_at' => '2026-08-18 09:32:37',
                'updated_at' => '2026-08-18 11:14:15',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => '<p>Selamat pagi.</p><p>Mohon dibantu informasi update bottom harga telur ayam kadang fresh hari ini tanggal 18/08/2026, untuk pengiriman tanggal 18/08/2026 dengan qty 450kg. Kami tunggu informasinya sampai dengan jam 12.00 WIB. Terima kasih</p>',
            ),
            46 => 
            array (
                'id' => 72,
                'project_id' => 94,
                'rfq_number' => 'RFQ-20260818-JPFE',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 4,
                'project_type' => 'purchase_request',
                'published_at' => '2026-08-18 09:32:57',
                'created_at' => '2026-08-18 09:35:13',
                'updated_at' => '2026-08-18 11:14:57',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => '<p>Selamat pagi.</p><p>Mohon dibantu informasi update bottom harga telur ayam kadang fresh hari ini tanggal 18/08/2026, untuk pengiriman tanggal 19/08/2026 dengan qty 1.200kg. Kami tunggu informasinya sampai dengan jam 12.00 WIB. Terima kasih</p>',
            ),
            47 => 
            array (
                'id' => 73,
                'project_id' => 96,
                'rfq_number' => 'RFQ-20260818-ZCNV',
                'type' => 'invited_only',
                'status' => 'published',
                'location_id' => 7,
                'project_type' => 'purchase_request',
                'published_at' => '2026-08-18 09:47:02',
                'created_at' => '2026-08-18 09:50:12',
                'updated_at' => '2026-08-18 09:50:12',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => '<p>Selamat pagi.</p><p>Mohon dibantu informasi update bottom harga telur ayam kadang fresh hari ini tanggal 18/08/2026, untuk pengiriman tanggal 19/08/2026 dengan qty 1.200kg. Kami tunggu informasinya sampai dengan jam 12.00 WIB. Terima kasih <br>TESTING</p>',
            ),
            48 => 
            array (
                'id' => 74,
                'project_id' => 97,
                'rfq_number' => 'RFQ-20260819-KLXH',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 4,
                'project_type' => 'purchase_request',
                'published_at' => '2026-08-19 10:18:40',
                'created_at' => '2026-08-19 10:22:14',
                'updated_at' => '2026-08-19 11:27:23',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => '<p>Selamat siang, Kami mohon informasi update bottom harga telur ayam fresh hari ini tgl 19/08/2026 , untuk pengiriman tgl 20/08/2026 dengan qty 1200kg. Kami tunggu informasinya sampai dengan jam 12.30 WIB. Terimakasih</p>',
            ),
            49 => 
            array (
                'id' => 75,
                'project_id' => 96,
                'rfq_number' => 'RFQ-20260819-V7XT',
                'type' => 'invited_only',
                'status' => 'cancelled',
                'location_id' => 7,
                'project_type' => 'project',
                'published_at' => '2026-08-19 13:37:57',
                'created_at' => '2026-08-19 13:42:02',
                'updated_at' => '2026-08-19 13:46:33',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => '<p></p>',
            ),
            50 => 
            array (
                'id' => 76,
                'project_id' => 99,
                'rfq_number' => 'RFQ-20260819-2M0B',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 7,
                'project_type' => 'project',
                'published_at' => '2026-08-19 13:58:47',
                'created_at' => '2026-08-19 13:59:59',
                'updated_at' => '2026-08-19 14:27:35',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => '<p>Selamat pagi.</p><p>Mohon dibantu informasi update bottom harga telur ayam kadang fresh hari ini tanggal 19/08/2026, untuk pengiriman tanggal 20/08/2026 dengan qty 300kg. Kami tunggu informasinya sampai dengan jam 12.00 WIB. Terima kasih</p>',
            ),
            51 => 
            array (
                'id' => 77,
                'project_id' => 100,
                'rfq_number' => 'RFQ-20260820-TAFS',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 4,
                'project_type' => 'purchase_request',
                'published_at' => '2026-08-20 10:52:36',
                'created_at' => '2026-08-20 10:55:07',
                'updated_at' => '2026-08-20 11:14:23',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => '<p>Selamat siang, Kami mohon informasi update bottom harga telur ayam fresh hari ini tgl 20/08/2026 , untuk pengiriman tgl 21/08/2026 dengan qty 1050kg. Kami tunggu informasinya sampai dengan jam 12.30 WIB. Terimakasih</p>',
            ),
            52 => 
            array (
                'id' => 78,
                'project_id' => 103,
                'rfq_number' => 'RFQ-20260820-LPVS',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 7,
                'project_type' => 'project',
                'published_at' => '2026-08-20 13:29:57',
                'created_at' => '2026-08-20 13:31:13',
                'updated_at' => '2026-08-20 14:20:11',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => '<p>Mohon informasi update bottom harga telur hari ini tanggal 20 Agustus 2026, dengan kuantiti 300kg untuk pengiriman besok di tanggal 21 Agustus 2026. Kami tunggu informasinya sampai jam 12.00 siang. Terimakasih</p>',
            ),
            53 => 
            array (
                'id' => 79,
                'project_id' => 104,
                'rfq_number' => 'RFQ-20260820-8SGN',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 7,
                'project_type' => 'purchase_request',
                'published_at' => '2026-08-20 14:25:53',
                'created_at' => '2026-08-20 14:37:03',
                'updated_at' => '2026-08-28 13:56:02',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => '<p></p>',
            ),
            54 => 
            array (
                'id' => 80,
                'project_id' => 105,
                'rfq_number' => 'RFQ-20260821-XY9V',
                'type' => 'invited_only',
                'status' => 'published',
                'location_id' => 4,
                'project_type' => 'purchase_request',
                'published_at' => '2026-08-21 09:48:41',
                'created_at' => '2026-08-21 10:04:08',
                'updated_at' => '2026-08-21 10:04:08',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => '<p></p>',
            ),
            55 => 
            array (
                'id' => 81,
                'project_id' => 106,
                'rfq_number' => 'RFQ-20260821-E0MM',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 4,
                'project_type' => 'purchase_request',
                'published_at' => '2026-08-21 13:08:29',
                'created_at' => '2026-08-21 13:10:12',
                'updated_at' => '2026-08-21 13:48:37',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => '<p>Selamat siang, Kami mohon informasi update bottom harga telur ayam fresh hari ini tgl 21/08/2026 , untuk pengiriman tgl 22/08/2026 dengan qty 1050kg. Kami tunggu informasinya sampai dengan jam 13.30 WIB. Terimakasih</p>',
            ),
            56 => 
            array (
                'id' => 82,
                'project_id' => 107,
                'rfq_number' => 'RFQ-20260821-MC6H',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 4,
                'project_type' => 'purchase_request',
                'published_at' => '2026-08-21 13:10:44',
                'created_at' => '2026-08-21 13:13:17',
                'updated_at' => '2026-08-21 13:49:37',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => '<p>Selamat siang, Kami mohon informasi update bottom harga telur ayam fresh hari ini tgl 21/08/2026 , untuk pengiriman tgl 24/08/2026 dengan qty 1200kg. Kami tunggu informasinya sampai dengan jam 13.30 WIB. Terimakasih</p>',
            ),
            57 => 
            array (
                'id' => 83,
                'project_id' => 110,
                'rfq_number' => 'RFQ-20260821-IEKZ',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 7,
                'project_type' => 'purchase_request',
                'published_at' => '2026-08-21 13:57:49',
                'created_at' => '2026-08-21 14:00:50',
                'updated_at' => '2026-08-21 14:36:51',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => '<p>Mohon informasi update bottom harga telur hari ini tanggal 21 Agustus 2026, dengan Quantity 350 KG untuk pengiriman besok di tanggal 22 Agustus 2026. Kami tunggu informasinya sampai jam 12.00 siang. Terimakasih</p>',
            ),
            58 => 
            array (
                'id' => 84,
                'project_id' => 111,
                'rfq_number' => 'RFQ-20260821-KCQR',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 7,
                'project_type' => 'purchase_request',
                'published_at' => '2026-08-21 14:00:50',
                'created_at' => '2026-08-21 14:03:39',
                'updated_at' => '2026-08-21 14:37:57',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => '<p>Mohon informasi update bottom harga telur hari ini tanggal 21 Agustus 2026, dengan Quantity 500KG untuk pengiriman besok di tanggal 24 Agustus 2026. Kami tunggu informasinya sampai jam 12.00 siang. Terimakasih</p>',
            ),
            59 => 
            array (
                'id' => 85,
                'project_id' => 112,
                'rfq_number' => 'RFQ-20260821-HVSE',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 4,
                'project_type' => 'purchase_request',
                'published_at' => '2026-08-21 17:12:54',
                'created_at' => '2026-08-21 17:20:35',
                'updated_at' => '2026-08-24 16:17:59',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => '<p></p>',
            ),
            60 => 
            array (
                'id' => 86,
                'project_id' => 113,
                'rfq_number' => 'RFQ-20260824-LFJA',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 7,
                'project_type' => 'purchase_request',
                'published_at' => '2026-08-24 11:38:19',
                'created_at' => '2026-08-24 11:47:07',
                'updated_at' => '2026-08-24 14:37:47',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => '<p>Mohon informasi update bottom harga telur hari ini tanggal 24 Agustus 2026, dengan Quantity 200 KG untuk pengiriman besok di tanggal 26 Agustus 2026. Kami tunggu informasinya sampai jam 12.00 siang. Terimakasih</p>',
            ),
            61 => 
            array (
                'id' => 87,
                'project_id' => 114,
                'rfq_number' => 'RFQ-20260826-XI70',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 4,
                'project_type' => 'purchase_request',
                'published_at' => '2026-08-26 08:58:41',
                'created_at' => '2026-08-26 09:02:14',
                'updated_at' => '2026-08-26 11:08:12',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => '<p>Selamat Pagi, Kami mohon informasi update bottom harga telur ayam fresh hari ini tgl 26/08/2026 , untuk pengiriman siang ini tgl 26/08/2026 dengan qty 600kg. Kami tunggu informasinya sampai dengan jam 10.30 WIB. Terimakasih</p>',
            ),
            62 => 
            array (
                'id' => 88,
                'project_id' => 115,
                'rfq_number' => 'RFQ-20260826-RGWP',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 4,
                'project_type' => 'purchase_request',
                'published_at' => '2026-08-26 11:47:40',
                'created_at' => '2026-08-26 11:49:53',
                'updated_at' => '2026-08-26 13:26:10',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => '<p>Selamat siang, Kami mohon informasi update bottom harga telur ayam fresh hari ini tgl 26/08/2026 , untuk pengiriman tgl 27/08/2026 dengan qty 1050kg. Kami tunggu informasinya sampai dengan jam 13.30 WIB. Terimakasih</p>',
            ),
            63 => 
            array (
                'id' => 89,
                'project_id' => 116,
                'rfq_number' => 'RFQ-20260827-F8AS',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 4,
                'project_type' => 'purchase_request',
                'published_at' => '2026-08-27 09:04:19',
                'created_at' => '2026-08-27 09:07:36',
                'updated_at' => '2026-08-27 10:10:42',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => '<p>Selamat siang, Kami mohon informasi update bottom harga telur ayam fresh hari ini tgl 27/08/2026 , untuk pengiriman siang hari ini tgl 27/08/2026 dengan qty 450kg. Kami tunggu informasinya sampai dengan jam 10.00 WIB. Terimakasih</p>',
            ),
            64 => 
            array (
                'id' => 90,
                'project_id' => 117,
                'rfq_number' => 'RFQ-20260827-0JF1',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 4,
                'project_type' => 'purchase_request',
                'published_at' => '2026-08-27 11:09:36',
                'created_at' => '2026-08-27 11:12:36',
                'updated_at' => '2026-08-27 13:45:35',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => '<p>Selamat siang, Kami mohon informasi update bottom harga telur ayam fresh hari ini tgl 27/08/2026 , untuk pengiriman tgl 28/08/2026 dengan qty 900kg. Kami tunggu informasinya sampai dengan jam 13.30 WIB. Terimakasih</p>',
            ),
            65 => 
            array (
                'id' => 91,
                'project_id' => 118,
                'rfq_number' => 'RFQ-20260827-VQ8P',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 7,
                'project_type' => 'purchase_request',
                'published_at' => '2026-08-27 11:19:01',
                'created_at' => '2026-08-27 11:22:30',
                'updated_at' => '2026-08-27 14:28:06',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => '<p>Mohon informasi update bottom harga telur hari ini tanggal 27 Agustus 2026, dengan Quantity 300 KG untuk pengiriman besok di tanggal 28 Agustus 2026. Kami tunggu informasinya sampai jam 12.00 siang. Terimakasih</p>',
            ),
            66 => 
            array (
                'id' => 92,
                'project_id' => 119,
                'rfq_number' => 'RFQ-20260827-4TYT',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 4,
                'project_type' => 'purchase_request',
                'published_at' => '2026-08-27 13:11:01',
                'created_at' => '2026-08-27 13:18:23',
                'updated_at' => '2026-09-02 15:04:44',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => '<p></p>',
            ),
            67 => 
            array (
                'id' => 93,
                'project_id' => 120,
                'rfq_number' => 'RFQ-20260827-HHZL',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 7,
                'project_type' => 'purchase_request',
                'published_at' => '2026-08-27 13:20:37',
                'created_at' => '2026-08-27 13:32:52',
                'updated_at' => '2026-09-02 17:18:20',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => '<p>Mohon informasi Harga Packaging natal sesuai lint, dengan Quantity tersebut. Kami tunggu informasinya sampai jam 12.00 siang. Terimakasih</p>',
            ),
            68 => 
            array (
                'id' => 94,
                'project_id' => 121,
                'rfq_number' => 'RFQ-20260827-NREG',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 7,
                'project_type' => 'purchase_request',
                'published_at' => '2026-08-27 13:33:08',
                'created_at' => '2026-08-27 13:40:20',
                'updated_at' => '2026-08-31 11:46:00',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => '<p>Mohon informasi Harga Kripik Pisang sesuai list, dengan Quantity tersebut. Kami tunggu informasinya sampai jam 12.00 siang. Terimakasih</p>',
            ),
            69 => 
            array (
                'id' => 95,
                'project_id' => 122,
                'rfq_number' => 'RFQ-20260827-NQBK',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 7,
                'project_type' => 'purchase_request',
                'published_at' => '2026-08-27 13:42:35',
                'created_at' => '2026-08-27 13:46:21',
                'updated_at' => '2026-08-28 16:41:58',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => '<p>Mohon informasi Harga Form Penerimaan Bank, dengan Quantity tersebut. Kami tunggu informasinya sampai jam 12.00 siang. Terimakasih</p>',
            ),
            70 => 
            array (
                'id' => 96,
                'project_id' => 123,
                'rfq_number' => 'RFQ-20260827-UPBC',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 4,
                'project_type' => 'purchase_request',
                'published_at' => '2026-08-27 14:15:54',
                'created_at' => '2026-08-27 14:41:08',
                'updated_at' => '2026-09-02 14:00:40',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => '<p></p>',
            ),
            71 => 
            array (
                'id' => 97,
                'project_id' => 124,
                'rfq_number' => 'RFQ-20260827-0CIT',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 7,
                'project_type' => 'purchase_request',
                'published_at' => '2026-08-27 15:32:44',
                'created_at' => '2026-08-27 16:36:11',
                'updated_at' => '2026-09-02 18:21:27',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => '<p></p>',
            ),
            72 => 
            array (
                'id' => 98,
                'project_id' => 125,
                'rfq_number' => 'RFQ-20260827-THOM',
                'type' => 'invited_only',
                'status' => 'published',
                'location_id' => 7,
                'project_type' => 'purchase_request',
                'published_at' => '2026-08-27 17:01:38',
                'created_at' => '2026-08-27 17:10:28',
                'updated_at' => '2026-08-27 17:10:28',
                'deleted_at' => NULL,
                'remark' => NULL,
            'external_notes' => '<p>Mohon informasi Harga Truck Tronton untuk Loading Jakarta (Taman Tekno)  ke Sidoarjo (Safe N Lock). Kami tunggu informasinya sampai jam 12.00 siang. Terimakasih</p>',
            ),
            73 => 
            array (
                'id' => 99,
                'project_id' => 126,
                'rfq_number' => 'RFQ-20260828-GRZG',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 4,
                'project_type' => 'purchase_request',
                'published_at' => '2026-08-28 10:52:37',
                'created_at' => '2026-08-28 10:53:46',
                'updated_at' => '2026-08-28 11:53:17',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => '<p>Selamat siang, Kami mohon informasi update bottom harga telur ayam fresh hari ini tgl 28/08/2026 , untuk pengiriman tgl 29/08/2026 dengan qty 900kg. Kami tunggu informasinya sampai dengan jam 13.30 WIB. Terimakasih</p>',
            ),
            74 => 
            array (
                'id' => 100,
                'project_id' => 127,
                'rfq_number' => 'RFQ-20260828-QABP',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 7,
                'project_type' => 'purchase_request',
                'published_at' => '2026-08-28 12:43:15',
                'created_at' => '2026-08-28 12:46:00',
                'updated_at' => '2026-08-28 15:21:30',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => '<p>Mohon informasi update bottom harga telur hari ini tanggal 28 Agustus 2026, dengan Quantity 400 KG untuk pengiriman besok di tanggal 31 Agustus 2026. Kami tunggu informasinya sampai jam 12.00 siang. Terimakasih</p>',
            ),
            75 => 
            array (
                'id' => 101,
                'project_id' => 128,
                'rfq_number' => 'RFQ-20260829-AWZB',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 7,
                'project_type' => 'purchase_request',
                'published_at' => '2026-08-29 19:26:03',
                'created_at' => '2026-08-29 19:37:42',
                'updated_at' => '2026-09-02 17:42:52',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => '<p></p>',
            ),
            76 => 
            array (
                'id' => 102,
                'project_id' => 129,
                'rfq_number' => 'RFQ-20260831-NARD',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 4,
                'project_type' => 'purchase_request',
                'published_at' => '2026-08-31 10:17:29',
                'created_at' => '2026-08-31 10:21:59',
                'updated_at' => '2026-08-31 11:17:06',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => '<p>Selamat siang, Kami mohon informasi update bottom harga telur ayam fresh hari ini tgl 31/08/2026 , untuk pengiriman tgl 31/08/2026 dengan qty 450kg. Kami tunggu informasinya sampai dengan jam 11.00 WIB. Terimakasih</p>',
            ),
            77 => 
            array (
                'id' => 103,
                'project_id' => 130,
                'rfq_number' => 'RFQ-20260831-HMVL',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 4,
                'project_type' => 'purchase_request',
                'published_at' => '2026-08-31 10:33:19',
                'created_at' => '2026-08-31 10:35:05',
                'updated_at' => '2026-08-31 11:52:29',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => '<p>Selamat siang, Kami mohon informasi update bottom harga telur ayam fresh hari ini tgl 31/08/2026 , untuk pengiriman tgl 01/09/2026 dengan qty 900kg. Kami tunggu informasinya sampai dengan jam 13.30 WIB. Terimakasih</p>',
            ),
            78 => 
            array (
                'id' => 104,
                'project_id' => 131,
                'rfq_number' => 'RFQ-20260831-AAWY',
                'type' => 'invited_only',
                'status' => 'negotiation',
                'location_id' => 4,
                'project_type' => 'purchase_request',
                'published_at' => '2026-08-31 11:28:05',
                'created_at' => '2026-08-31 11:40:41',
                'updated_at' => '2026-09-03 16:04:06',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => '<p></p>',
            ),
            79 => 
            array (
                'id' => 105,
                'project_id' => 132,
                'rfq_number' => 'RFQ-20260831-WC7H',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 7,
                'project_type' => 'purchase_request',
                'published_at' => '2026-08-31 11:56:20',
                'created_at' => '2026-08-31 12:04:11',
                'updated_at' => '2026-08-31 18:08:52',
                'deleted_at' => NULL,
                'remark' => 'Mohon informasi update bottom harga telur hari ini tanggal 31 Agustus 2026, dengan kuantiti 500kg untuk pengiriman besok di tanggal 1 September 2026. Kami tunggu informasinya sampai jam 13.30 siang. Terima kasih',
                'external_notes' => '<p></p>',
            ),
            80 => 
            array (
                'id' => 106,
                'project_id' => 133,
                'rfq_number' => 'RFQ-20260831-MCE7',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 4,
                'project_type' => 'purchase_request',
                'published_at' => '2026-08-31 14:11:01',
                'created_at' => '2026-08-31 14:29:20',
                'updated_at' => '2026-09-02 10:42:42',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => '<p></p>',
            ),
            81 => 
            array (
                'id' => 107,
                'project_id' => 134,
                'rfq_number' => 'RFQ-20260901-ZZCA',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 4,
                'project_type' => 'purchase_request',
                'published_at' => '2026-09-01 11:16:21',
                'created_at' => '2026-09-01 11:19:54',
                'updated_at' => '2026-09-01 13:06:52',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => '<p>Selamat siang, Kami mohon informasi update bottom harga telur ayam fresh hari ini tgl 01/08/2026 , untuk pengiriman tgl 02/09/2026 dengan qty 900kg. Kami tunggu informasinya sampai dengan jam 13.30 WIB. Terimakasih</p>',
            ),
            82 => 
            array (
                'id' => 108,
                'project_id' => 135,
                'rfq_number' => 'RFQ-20260901-N99T',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 7,
                'project_type' => 'purchase_request',
                'published_at' => '2026-09-01 11:32:49',
                'created_at' => '2026-09-01 11:36:53',
                'updated_at' => '2026-09-01 13:50:43',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => '<p>Mohon informasi update bottom harga telur hari ini tanggal 01 September 2026, dengan kuantiti 400kg untuk pengiriman besok di tanggal 1 September 2026. Kami tunggu informasinya sampai jam 13.30 siang. Terima kasih</p>',
            ),
            83 => 
            array (
                'id' => 109,
                'project_id' => 136,
                'rfq_number' => 'RFQ-20260901-J4LL',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 4,
                'project_type' => 'purchase_request',
                'published_at' => '2026-09-01 13:47:37',
                'created_at' => '2026-09-01 13:55:16',
                'updated_at' => '2026-09-02 15:52:44',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => '<p></p>',
            ),
            84 => 
            array (
                'id' => 110,
                'project_id' => 137,
                'rfq_number' => 'RFQ-20260901-XBSB',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 7,
                'project_type' => 'purchase_request',
                'published_at' => '2026-09-01 15:45:43',
                'created_at' => '2026-09-01 16:01:01',
                'updated_at' => '2026-09-03 10:21:24',
                'deleted_at' => NULL,
                'remark' => NULL,
            'external_notes' => '<p>Dear Vendor MWT Teknik <br><br>Selamat Sore , <br>Mohon dapat di bantu membuatkan penawaran harga Rak Stainles Dengan bahan 304. <br><br>Atas kerja sama yang baik, saya sampaikan terima kasih. <br><br>Warm Regards,<br>Procurement Department (Putri Jatim)</p>',
            ),
            85 => 
            array (
                'id' => 111,
                'project_id' => 138,
                'rfq_number' => 'RFQ-20260902-JYHA',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 4,
                'project_type' => 'purchase_request',
                'published_at' => '2026-09-02 10:38:28',
                'created_at' => '2026-09-02 10:41:24',
                'updated_at' => '2026-09-02 11:06:50',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => '<p>Selamat siang, Kami mohon informasi update bottom harga telur ayam fresh hari ini tgl 02/08/2026 , untuk pengiriman tgl 03/09/2026 dengan qty 900kg. Kami tunggu informasinya sampai dengan jam 13.30 WIB. Terimakasih</p>',
            ),
            86 => 
            array (
                'id' => 112,
                'project_id' => 139,
                'rfq_number' => 'RFQ-20260902-HVNP',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 4,
                'project_type' => 'purchase_request',
                'published_at' => '2026-09-02 11:02:25',
                'created_at' => '2026-09-02 11:05:53',
                'updated_at' => '2026-09-07 16:38:47',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => '<p></p>',
            ),
            87 => 
            array (
                'id' => 113,
                'project_id' => 140,
                'rfq_number' => 'RFQ-20260902-AUSI',
                'type' => 'invited_only',
                'status' => 'negotiation',
                'location_id' => 4,
                'project_type' => 'purchase_request',
                'published_at' => '2026-09-02 11:12:52',
                'created_at' => '2026-09-02 11:19:21',
                'updated_at' => '2026-09-02 13:26:03',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => '<p></p>',
            ),
            88 => 
            array (
                'id' => 114,
                'project_id' => 141,
                'rfq_number' => 'RFQ-20260902-MCOD',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 7,
                'project_type' => 'purchase_request',
                'published_at' => '2026-09-02 11:17:04',
                'created_at' => '2026-09-02 11:21:41',
                'updated_at' => '2026-09-02 14:53:13',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => '<p>Mohon informasi update bottom harga telur hari ini tanggal 02 September 2026, dengan kuantiti 200kg untuk pengiriman besok di tanggal 3 September 2026. Kami tunggu informasinya sampai jam 13.30 siang. Terima kasih</p>',
            ),
            89 => 
            array (
                'id' => 115,
                'project_id' => 142,
                'rfq_number' => 'RFQ-20260902-LKBD',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 4,
                'project_type' => 'purchase_request',
                'published_at' => '2026-09-02 13:34:23',
                'created_at' => '2026-09-02 13:46:46',
                'updated_at' => '2026-09-02 16:07:37',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => '<p></p>',
            ),
            90 => 
            array (
                'id' => 116,
                'project_id' => 143,
                'rfq_number' => 'RFQ-20260902-FKWT',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 7,
                'project_type' => 'purchase_request',
                'published_at' => '2026-09-02 13:34:39',
                'created_at' => '2026-09-02 13:48:47',
                'updated_at' => '2026-09-03 11:38:43',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => '<p>Dear Vendor PT. Fajar Putra Plasindo<br><br>Selamat Siang,<br>Mohon dapat di bantu membuatkan penawaran harga<br><br>Atas kerja sama yang baik, saya sampaikan terima kasih.<br><br>Warm Regards,<br>Procurement Department</p>',
            ),
            91 => 
            array (
                'id' => 117,
                'project_id' => 145,
                'rfq_number' => 'RFQ-20260903-EM4D',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 4,
                'project_type' => 'purchase_request',
                'published_at' => '2026-09-03 10:15:55',
                'created_at' => '2026-09-03 10:18:56',
                'updated_at' => '2026-09-03 13:39:33',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => '<p>Selamat siang, Kami mohon informasi update bottom harga telur ayam fresh hari ini tgl 03/08/2026 , untuk pengiriman tgl 04/09/2026 dengan qty 750kg. Kami tunggu informasinya sampai dengan jam 13.30 WIB. Terimakasih</p>',
            ),
            92 => 
            array (
                'id' => 118,
                'project_id' => 146,
                'rfq_number' => 'RFQ-20260903-PNDQ',
                'type' => 'invited_only',
                'status' => 'negotiation',
                'location_id' => 4,
                'project_type' => 'purchase_request',
                'published_at' => '2026-09-03 10:10:47',
                'created_at' => '2026-09-03 10:19:30',
                'updated_at' => '2026-09-05 21:34:17',
                'deleted_at' => NULL,
                'remark' => 'PR-PD-26-08-5240 & PR-PD-26-08-5248',
                'external_notes' => '<p></p>',
            ),
            93 => 
            array (
                'id' => 119,
                'project_id' => 147,
                'rfq_number' => 'RFQ-20260903-AP4G',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 4,
                'project_type' => 'purchase_request',
                'published_at' => '2026-09-03 10:35:04',
                'created_at' => '2026-09-03 10:38:50',
                'updated_at' => '2026-09-08 14:21:46',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => '<p></p>',
            ),
            94 => 
            array (
                'id' => 120,
                'project_id' => 148,
                'rfq_number' => 'RFQ-20260903-UL7S',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 7,
                'project_type' => 'purchase_request',
                'published_at' => '2026-09-03 12:01:46',
                'created_at' => '2026-09-03 12:06:01',
                'updated_at' => '2026-09-03 13:43:05',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => '<p>Mohon informasi update bottom harga telur hari ini tanggal 03 September 2026, dengan kuantiti 250KG untuk pengiriman besok di tanggal 04 September 2026. Kami tunggu informasinya sampai jam 13.30 siang. Terima kasih</p>',
            ),
            95 => 
            array (
                'id' => 121,
                'project_id' => 149,
                'rfq_number' => 'RFQ-20260904-OLST',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 4,
                'project_type' => 'purchase_request',
                'published_at' => '2026-09-04 11:23:07',
                'created_at' => '2026-09-04 11:28:32',
                'updated_at' => '2026-09-04 13:33:16',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => '<p>Selamat siang, Kami mohon informasi update bottom harga telur ayam fresh hari ini tgl 04/08/2026 , untuk pengiriman tgl 05/09/2026 dengan qty 750kg. Kami tunggu informasinya sampai dengan jam 13.30 WIB. Terimakasih</p>',
            ),
            96 => 
            array (
                'id' => 122,
                'project_id' => 150,
                'rfq_number' => 'RFQ-20260904-ZV0F',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 4,
                'project_type' => 'purchase_request',
                'published_at' => '2026-09-04 11:33:56',
                'created_at' => '2026-09-04 11:36:53',
                'updated_at' => '2026-09-04 13:32:42',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => '<p>Selamat siang, Kami mohon informasi update bottom harga telur ayam fresh hari ini tgl 04/08/2026 , untuk pengiriman tgl 07/09/2026 dengan qty 900kg. Kami tunggu informasinya sampai dengan jam 13.30 WIB. Terimakasih</p>',
            ),
            97 => 
            array (
                'id' => 123,
                'project_id' => 151,
                'rfq_number' => 'RFQ-20260904-LXJ7',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 7,
                'project_type' => 'purchase_request',
                'published_at' => '2026-09-04 13:38:16',
                'created_at' => '2026-09-04 13:43:41',
                'updated_at' => '2026-09-04 14:46:51',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => '<p>Mohon informasi update bottom harga telur hari ini tanggal 04 September 2026, dengan kuantiti 250KG untuk pengiriman besok di tanggal 07 September 2026. Kami tunggu informasinya sampai jam 13.30 siang. Terima kasih</p>',
            ),
            98 => 
            array (
                'id' => 124,
                'project_id' => 152,
                'rfq_number' => 'RFQ-20260907-49GC',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 4,
                'project_type' => 'purchase_request',
                'published_at' => '2026-09-07 10:33:27',
                'created_at' => '2026-09-07 10:36:02',
                'updated_at' => '2026-09-07 11:19:09',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => '<p>Selamat siang, Kami mohon informasi update bottom harga telur ayam fresh hari ini tgl 07/08/2026 , untuk pengiriman tgl 08/09/2026 dengan qty 600kg. Kami tunggu informasinya sampai dengan jam 13.30 WIB. Terimakasih</p>',
            ),
            99 => 
            array (
                'id' => 125,
                'project_id' => 153,
                'rfq_number' => 'RFQ-20260907-S4ZB',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 4,
                'project_type' => 'purchase_request',
                'published_at' => '2026-09-07 11:21:40',
                'created_at' => '2026-09-07 11:39:08',
                'updated_at' => '2026-09-07 15:55:07',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => '<p></p>',
            ),
            100 => 
            array (
                'id' => 126,
                'project_id' => 154,
                'rfq_number' => 'RFQ-20260907-GEOK',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 7,
                'project_type' => 'purchase_request',
                'published_at' => '2026-09-07 11:33:43',
                'created_at' => '2026-09-07 11:41:20',
                'updated_at' => '2026-09-07 13:49:59',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => '<p>Mohon informasi update bottom harga telur hari ini tanggal 07 September 2026, dengan kuantiti 300KG untuk pengiriman besok di tanggal 08 September 2026. Kami tunggu informasinya sampai jam 13.30 siang. Terima kasih</p>',
            ),
            101 => 
            array (
                'id' => 127,
                'project_id' => 157,
                'rfq_number' => 'RFQ-20260907-AYOU',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 4,
                'project_type' => 'purchase_request',
                'published_at' => '2026-09-07 14:34:31',
                'created_at' => '2026-09-07 14:35:54',
                'updated_at' => '2026-09-07 15:01:50',
                'deleted_at' => NULL,
                'remark' => 'internal remark rfq',
                'external_notes' => '<p>This is external notes for</p><h2><strong>RFQ</strong></h2>',
            ),
            102 => 
            array (
                'id' => 128,
                'project_id' => 158,
                'rfq_number' => 'RFQ-20260908-SGNV',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 4,
                'project_type' => 'purchase_request',
                'published_at' => '2026-09-08 09:14:19',
                'created_at' => '2026-09-08 09:20:09',
                'updated_at' => '2026-09-08 10:53:13',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => '<p>Selamat pagi, Kami mohon informasi update bottom harga telur ayam fresh hari ini tgl 08/09/2026 , untuk pengiriman tgl 08/09/2026 dengan qty 300kg. Kami tunggu informasinya sampai dengan jam 10.00 WIB. Terimakasih</p>',
            ),
            103 => 
            array (
                'id' => 129,
                'project_id' => 159,
                'rfq_number' => 'RFQ-20260908-EX9C',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 4,
                'project_type' => 'purchase_request',
                'published_at' => '2026-09-08 09:21:23',
                'created_at' => '2026-09-08 09:24:20',
                'updated_at' => '2026-09-08 10:53:46',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => '<p>Selamat pagi, Kami mohon informasi update bottom harga telur ayam fresh hari ini tgl 08/09/2026 , untuk pengiriman tgl 09/09/2026 dengan qty 900kg. Kami tunggu informasinya sampai dengan jam 13.30WIB. Terimakasih</p>',
            ),
            104 => 
            array (
                'id' => 130,
                'project_id' => 160,
                'rfq_number' => 'RFQ-20260908-74AL',
                'type' => 'invited_only',
                'status' => 'awarded',
                'location_id' => 7,
                'project_type' => 'purchase_request',
                'published_at' => '2026-09-08 10:50:08',
                'created_at' => '2026-09-08 10:58:04',
                'updated_at' => '2026-09-08 13:40:30',
                'deleted_at' => NULL,
                'remark' => NULL,
                'external_notes' => '<p>Mohon informasi update bottom harga telur hari ini tanggal 08 September 2026, dengan kuantiti 300KG untuk pengiriman besok di tanggal 09 September 2026. Kami tunggu informasinya sampai jam 13.30 siang. Terima kasih</p>',
            ),
            105 => 
            array (
                'id' => 131,
                'project_id' => 161,
                'rfq_number' => 'RFQ-20260908-C27V',
                'type' => 'invited_only',
                'status' => 'published',
                'location_id' => 4,
                'project_type' => 'purchase_request',
                'published_at' => '2026-09-08 16:57:27',
                'created_at' => '2026-09-08 16:58:36',
                'updated_at' => '2026-09-08 16:58:36',
                'deleted_at' => NULL,
                'remark' => 'internal remark rfq2',
                'external_notes' => '<h3>Test RFQ IT2</h3>',
            ),
        ));
        
        
    }
}